//<auto-generated />

namespace VRT.Payments.Gateways.PayU.Services.DataContracts;
internal static class CancelOrder
{
    public sealed class Response
    {
        public string orderId { get; set; }
        public string extOrderId { get; set; }
        public Shared.Status status { get; set; }        
    }
}

