//<auto-generated />

namespace VRT.Payments.Gateways.PayU.Services.DataContracts;
internal static class GetOrder
{
    public class Response 
    {        
        public Shared.Order[] orders { get; set; }
        public Shared.Status status { get; set; }        
    }
}
